### ISSUE TITLE
Suggestion: Replace /compiled module prefix with instructions on modifying Babel exclusions.

### ISSUE THREAD

**Issue by threehams** [TrueCar/gluestick#1028]
I'm not sure how best to handle this one overall, so I'll just open up discussion.

Right now, to include something in node_modules within Babel compilation, we need to do this:

```
import { Button } from "compiled/library-name";
```

This works for simpler cases, but doesn't go so well when using a library like this in many, many places. It requires Flow module mappings, interferes with some Babel plugins since it's a Webpack alias, increases the size of the library name (in our case, it's now _huge_). Typescript may not work at all since it's not aware of Webpack's aliases.

Unless this is a convention used in other projects, I'd suggest that we have instructions for how to whitelist a module for Babel compilation within Gluestick's docs. We could keep support for `compiled/` since it's in use, but possible deprecate it or drop the documentation for it.

**Comment by threehams** [comment]
Relevant line in webpack.config.js:
```
exclude: new RegExp(`(node_modules/(?!gluestick))|(${buildAssetsPath})`),
```
It's possible to modify this, but it's also very risky, and would make any changes to this line a potential breaking change.

Maybe add something to configuration? I think we're trying to get away from that, but I'm not sure how else to handle this.

**Comment by zamotany** [comment]
`compiled` alias is mainly used to unmark modules as `external` so that renderer process won't carsh. We use `universal-webpack` to tweak renderer webpack configuation, because we don't need to have most of the modules bundled, it runs on node so they can be easily `require`'d.

IMO, every package that lands in npm registry **SHOULD** be transpiled and ready to use, but some doesn't do that or they don't feel like figuring out build process. Besides, if the package is transpiled before publishing, compilation time will be decreased.

But still, even if the package is transpiled in the first place, it doesn't solve SSR problem: we need to exclude styles (css, sass, etc) from renderer bundle. Right now we use `igonre-loader` for that.

Btw, the line posted above is not really relevant.

It's possible to code the solution that will allow to set what should be unmarked as `external` in configuration file, but it's an implicit solution, and potential source of confusion: why this works and the other thing does not.

**Comment by threehams** [comment]
There's a lot going on here I didn't see on first pass. The library this is affecting is Battery Pack (internal to TrueCar) which uses SCSS imports - I was keeping it a bit more general since this is a public issue.

This sounds like it's going to be easier to solve with a Babel plugin on the app side.

**Comment by threehams** [comment]
Can handle this at the app level. Closing.
