### ISSUE TITLE
Allow inserting redux middleware before promiseMiddleware and thunk

### ISSUE THREAD

**Issue by chrischen** [TrueCar/gluestick#126]
I currently insert middleware before promiseMiddleware so that it can modify isomorphic-fetch request hostnames so they can be called universally from the server (via absolute URL) or the client (via relative URL).

**Comment by toddw** [comment]
@chrischen absolute vs relative url on the server/client is handled automatically for you now via https://github.com/TrueCar/gluestick-shared/blob/master/src/lib/getHttpClient.js#L34

We do not currently support adding middleware before promiseMiddleware simply because the lack of a use case but would be happy to consider a PR if one was submitted.

Closing this issue for now since the reason for your request should no longer be an issue.

Thanks!

**Comment by toddw** [comment]
Related, I believe this will give you the power to add middleware in any order you would like: https://github.com/TrueCar/gluestick-shared/pull/55
