### ISSUE TITLE
Outdated .babelrc message

### ISSUE THREAD

**Issue by christinebrass** [TrueCar/gluestick#146]
If a Gluestick app has updated its .babelrc file to include a new plugin (for example), a message will appear during `gluestick start` that their .babelrc file is outdated:

```
› gluestick start
...
? The format of .babelrc is out of date. Would you like to automatically update it? (Y/n)
```

Sometimes an app will want to use additional configuration options or plugins not specified here: https://github.com/TrueCar/gluestick/blob/develop/templates/new/.babelrc. We need to prevent the message from appearing in that case.

**Comment by toddw** [comment]
They are currently getting a message? or is this to track that they _should_ get a message? It feels like applications should have control over their own .babelrc file. Does that currently mean things will break if .babelrc is removed or tweaked? (I'm thinking about HMR specifically). We should handle that gracefully so that HMR is technically optional and it shouldn't crash if they removed the babel plugins.

**Comment by christinebrass** [comment]
@toddw updated the issue's description to describe the case I'm considering.

**Comment by toddw** [comment]
> We need to prevent the message from appearing in that case.
