### ISSUE TITLE
Action generator

### ISSUE THREAD

**Issue by michalchudziak** [TrueCar/gluestick#420]
Have you considered adding action generator? Are there any blockers? Maybe we could implement it as well 🙂?

**Comment by toddw** [comment]
We considered it but it felt like it would an empty file. In most of the projects I've been working in, there was a file in like _src/actions/_subject_.js_ and in there you would just write things like:
```
export function loadSubject () {}
export function addSubject () {}
```

Definitely not opposed to it but not sure what a generated action would look like. Open to suggestions, what do you think it should look like? :)

**Comment by michalchudziak** [comment]
Maybe something like:
```js
export const SAMPLE_ACTION = 'SAMPLE_ACTION';

export function sampleActionCreator() {
  return {
    type: SAMPLE_ACTION,
  }
}
```
But yeah - I agree that it might be a bit useless, however, I feel like something is missing without action creator, especially if we have one for reducers.

What do you think?

**Comment by grabbou** [comment]
@toddw it could return a simple action instead of being an empty function with a `void` return type. Could return `FSA` to enforce patterns with a description (if that's following your approach here).

Also, anyone considered using `flow` instead of action constants? (quite crazy idea at this stage, but worth considering)

**Comment by toddw** [comment]
@mike866 I have no problem with generating an action. In our apps, we typically have 1 file with multiple actions in it related to the reducer. So if your reducer is something like `notes` then you would have a file _src/actions/notes.js_ where all of the notes actions would live.

I'm trying to understand how the action creator generator would work. Are you envisioning 1 file per action creator? Or would you need to specify the file for each one?

What would the CLI interaction look like?

If we have decent answers to these questions then I'm not against a generator for action creators. The template that you proposed looks like it could work

**Comment by toddw** [comment]
@grabbou 
>@toddw it could return a simple action instead of being an empty function with a void return type. Could return FSA to enforce patterns with a description (if that's following your approach here).

I'm onboard with returning FSA!

> Also, anyone considered using flow instead of action constants? (quite crazy idea at this stage, but worth considering)

I really like this idea, but currently the promise middleware triggers multiple actions by appending `_INIT` and sometimes `_FAILURE` when it fails. https://github.com/TrueCar/gluestick-shared/blob/master/src/lib/promiseMiddleware.js

I'm not saying I love this, in fact I kind of don't like that the constants currently have to equal strings. I'm definitely willing to change it. We would need to support backward compatibility on this one at least for a little while to give our apps time to update.

How would promise middleware work if we were to use flow types? I suppose this is where redux-saga could come into play but I kind of like how simple the promise middleware is for simple tasks.

**Comment by grabbou** [comment]
@toddw so with the flow being used instead of action constants, what I really meant is replacing e.g.:
```js
const SEND_EVENT = 'send_event';

export function sendEvent() {
   return {
      type: SEND_EVENT,
   };
}
```

with:
```js
export function sendEvent() {
   return { type: 'SEND_EVENT' }
}
```

Now, the approach would have no constants, meaning in reducers, when dealing with `async` action, you'd rather have to either:
1) type manually: `'SEND_EVENT_FAILURE'`
2) use a helper we create: `fail('SEND_EVENT')`

We could potentially hide it behind a flag, but it might be tricky to introduce it at this point to legacy code, mainly because it's a fundamentally different way of ensuring that actions are handled properly. 

What we could do however is to type entire app with Redux. This is mainly an inspiration that I have from [my article](https://blog.callstack.io/typed-redux-2aa8bff926ff) , however that stuff is still considered experimental, so I think it deserves a separate issue! What I like about it is that `connect()` is typed, amongst things like mapping state to props being described with types making it no longer required to open up reducer file to glance its structure.

**Comment by grabbou** [comment]
Going back to @mike866 discussion, looks like there are still some questions raised by @toddw that @mike866 we have to address :)
