### ISSUE TITLE
Docs setup

### ISSUE THREAD

**Issue by michalchudziak** [TrueCar/gluestick#422]
I have feeling that docs are quite raw. How about gathering some ideas to make it more user-friendly and informative?

**Comment by ferrannp** [comment]
Right now docs point to https://www.drivenbycode.com/getting-started-with-gluestick/ which it might be / will be out of date? Maybe we can go with [GitBook](https://www.gitbook.com/) or similar.

**Comment by grabbou** [comment]
Yeah. I suggest we set up Redux like approach with Gitbook powered documentation deployed to `gh-pages` by CircleCI on every pull-request.

We have that set up in place internally so it's just a matter of porting.

Can take it, curious whats @toddw take on that.

**Comment by toddw** [comment]
@grabbou @ferrannp The blog post is very out of date. I would be very happy with GitBook/gh-pages. Whatever you think will have the lowest amount of friction. I feel like Redux's documentation is one of the best written that I've read.

A while back we did create something on gitbooks.com just to check it out but we never made it every far. For now it's just a copy of the README which was really just set up as a placeholder. https://www.gitbook.com/book/toddw/gluestick

I added @grabbou, I couldn't find an account to link for @ferrannp but @grabbou should have access to inviting all of you.

Is there an advantage to having it deployed to `gh-pages` vs GitBook, are those one in the same?

**Comment by lukewalczak** [comment]
Can You give me and @olya646 permission to GitBook ?

**Comment by grabbou** [comment]
@lukewalczak @olya646 Let's discuss that once again tomorrow as we do not need GitBook permissions to roll it out. What we can do instead is to make gitbook cli build the docs locally on the CI machine and ship them to `gh-pages`, so they are available under github.io domain (just like Redux does). I think it's better to connect documentation with the repo itself (have a top-level `docs` folder) instead of a 3rd party service that has to be checked over and over to update the docs. Also, having a local build of gitbook makes it easy for us to apply any custom styling tweaks we can think of :) 

We already have a working setup in place, will be happy to follow-up with it tomorrow.

**Comment by toddw** [comment]
@grabbou This sounds great!

**Comment by grabbou** [comment]
@toddw can you please turn on Github pages for the `gh-pages` branch?

**Comment by toddw** [comment]
Should be set up now http://truecar.github.io/gluestick/

**Comment by olga32123** [comment]
Added some docs from blog
