### ISSUE TITLE
Should we support multiple versions of the CLI?

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#429]
Imagine you have multiple apps built with GlueStick that are running with separate versions. Since we are possibly about to introduce some breaking versions moving forward, maybe we should make it possible to run multiple versions of GlueStick CLI? How does the react-native cli solve this problem?

It's a bit tricky since it's a global binary, otherwise we could just make it a project dependency

**Comment by michalchudziak** [comment]
I think in this kind of situation user can choose a specific version of GlueStick from npm with `npm i -g gluestick@version`. 

I would leave it as it is now, but I'm open to further discussion.

**Comment by zamotany** [comment]
Another option that I often see is to have 2 spearate packages, in out case it would be: `gluestick` and `gluestick-cli`. `gluestick` package will be a dependency of specific project and `gluestick-cli` would be a global package that just executes tasks/commands from that local package. In that case only interface between `gluestick` and `gluestick-cli` must remain stable.

**Comment by toddw** [comment]
@zamotany that's _kind of_ what we have going on with `gluestick-shared`

**Comment by zamotany** [comment]
@toddw yeah, but I'm talking about fully moving logic, commands etc to project as a dependency

**Comment by toddw** [comment]
okay yeah that makes sense

**Comment by zamotany** [comment]
that way we won't have to worry about backwards compatibility at all, since everything resides in project dependencies

plus updating existing project would be a matter of installing new `gluestick-cli`, running `gluestick update` that will add `gluestick` do `package.json` as a dependency and run `npm install`. theroretically everything should work the same.

**Comment by grabbou** [comment]
How we solved this in RN:

You install a package `react-native-cli` that is just a single-line executable. It detects whether you are in a react-native project, and if yes, it calls into node_modules/react-native/local-cli. That way, CLI is always project specific.

To me, it would be great to have it as a dependency, so that I can choose when to update.

**Comment by grabbou** [comment]
Oh, I just see that this is exactly what @zamotany already said. My plus one goes to that. Would be happy to help with working on that.

Also, that would enable us to support plug-in architecture and abstract away things like redux from `gluestick` itself. We could mimic plugins support that we have made in React Native, which is when you have `gluestick-plugin-redux` in your project dependencies and that plugin adds e.g. redux generators, like reducer and action, they will be listed in `gluestick --help`. That way, we can support `redux`, `mobx` and `pure`.

This is more a feature towards open source community as I imagine that TrueCar is invested in Redux.

**Comment by toddw** [comment]
sounds good! let's do it!

**Comment by grabbou** [comment]
Great, I am going to take care of that, plugins and mono-repo since that's more-or-less what I was already up to. For now, I am going to focus on setting proper arch in place, will come up with a better and more detailed plan next week.

**Comment by zamotany** [comment]
Closed as no longer needed due to structure change here #470
