### ISSUE TITLE
`gluestick new` success message

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#442]
It would be nice if the output of `gluestick new ____` finished with a success message. Something like react-native-cli.

Example from react-native-cli
```
To run your app on iOS:
   react-native run-ios
   - or -
   Open ios/RNTest.xcodeproj in Xcode
   Hit the Run button
To run your app on Android:
   Have an Android emulator running (quickest way to get started), or a device connected
   react-native run-android
```

Maybe simpler though:
```
New GlueStick project created at _./new-project-name_.
To run your app and start developing:
cd new-project-name
gluestick start
open browser to http://localhost:8888/
```

Open to suggestions

**Comment by grabbou** [comment]
Makes a lot of sense. I was also thinking that it would be good to enhance the user experience with more messages etc., but you mentioned some `rails` - compat so that your backend guys feel familiar with the experience.

Is there a reference we can take a look at to provide better suggestions on how the `welcome` message could be phrased like?

**Comment by toddw** [comment]
The message in https://github.com/TrueCar/gluestick/pull/450 looks good to me with the 1 change I requested on the PR.

Rails actually doesn't have a message on `rails new projectName` other than the bundle install output. It is true that I try to learn lessons from Rails but the analogy doesn't always map to a javascript/front-end project.
