### ISSUE TITLE
Move generated app to use Jest as test solution

### ISSUE THREAD

**Issue by ferrannp** [TrueCar/gluestick#447]
Following #406. We can remove all other dependencies and use also Jest in generated app (recommended by community and used it in React and Redux projecst). User can also choose to use Snapshots if they want too (maybe we could pass a flag to generate snapshot test if they want to).

This will also fix #333 since we won't need istanbul anymore.

This depends on following PR: #437 & #445

**Comment by grabbou** [comment]
How that would provide a backwards-compatible environment for existing apps? I imagine it's not easy. Maybe a flag `experimental` to run `jest` tests only and make time for codebases to upgrade?

**Comment by grabbou** [comment]
( @toddw I think it could ship as a plugin at some point, kinda `gluestick-compat` that has pre-jest tests etc. )

**Comment by toddw** [comment]
If more people were using GlueStick outside of TrueCar then `gluestick-compat` would probably be worth the effort. Since we are still pre 1.0 and TrueCar is the only known user in production I'm happy with 1.0 breaking backwards compatibility. We will update our apps as needed. To help with that: https://github.com/skovhus/jest-codemods

If anyone watching this project has objections, please let use know and I think it would help change our mind.

**Comment by toddw** [comment]
We need to make sure we can debug tests in the generated apps. A comment on the node-inspector PR mentioned that it only works for individual tests. If that is true we need to at least support that but ideally it would be nice to be able to debug anywhere you want to.

https://github.com/TrueCar/gluestick/pull/445#issuecomment-274638831

**Comment by zamotany** [comment]
Generated apps should be fine, I tested it and debugging all test at one works.
But when debugging with Jest `--env jestEnvironmentNodeDebug.js` (similarly as npm **debug** script in gluestick) still needs to be passed though.

Plus `--debug-brk` **must** be used, because `debugger;` statements are omitted if inspector i**s not connected**.
