### ISSUE TITLE
Removing Axios from Gluestick

### ISSUE THREAD

**Issue by lukewalczak** [TrueCar/gluestick#468]

**Comment by lukewalczak** [comment]
As I see in Gluestick, Axios library isn't used. Do we need it in package.json or can remove it ?

**Comment by lukewalczak** [comment]
It's using in `gluestick-shared` and we suggest two options how to solve it:
1. move `axios` in gluestick-shared from `devDependencies` to `dependencies`,
2. using `fetch` instead of `axios` - for long-term fetch will be better option since Chrome already implemented it and implementation in other browsers is in development.

**Comment by michalchudziak** [comment]
I'd rather go for second option.

**Comment by ferrannp** [comment]
But even if you go for second option you probably need https://github.com/github/fetch if you want to support more browsers (I am talking about IE). That dependency uses native `fetch` if it is supported or the polyfill otherwise. But I agree this seems a more natural path since in the future we might go just good using the native fetch.

**Comment by toddw** [comment]
Currently we do a lot of things to customize axios… For example we take advantage of the ability to add request and response hooks for our frontend apps. Many of our backend APIs are built with Rails and they use snake_case and our javascript apps use camelCase. With those hooks we automatically transform requests and responses so that we don't have to do so in app code. Is this possible with `fetch`?

The reason for keeping axios around at least in `templates/new/package.json` is so that our apps will be able to use it.

**Comment by zamotany** [comment]
There are multiple ways to achieve that.
For example:
```
fetch('url', { ... }).then(response => {
  return response.json();
}).then(...);
```
1. Replace arrow function with custom one, that will do `response.json()` then execute hooks (interceptors) that will return promise
2. use for instance [fetch-intercept](https://www.npmjs.com/package/fetch-intercept)
3. write own wrapper on fetch that supports hooks/interceptors - it's like 30 lines of code

**Comment by toddw** [comment]
I'm fine with moving to fetch as long as we maintain the ability to add hooks/interceptors. fetch-intercept looks like a good choice. Also, we should include the polyfill for older browsers. Any ideas on how we could only include the polyfill when it is needed?

**Comment by zamotany** [comment]
We would use `isomorphic-fetch` which is also a polyfill and it's ~3KB gzip'ed. The only option I'm aware of about providing polyfill only when needed is to use user agent.

**Comment by toddw** [comment]
What about conditional comments?
```
<!--[if IE]--><script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.2/fetch.min.js"></script><!--[endif]-->
```

Does anyone use these still? Is there a reason not to?

I'm okay with including the polyfill being 3kb because axios minified and gzipped is 4kb and it would eliminate the need to include that. So we would be 1kb smaller than before

**Comment by zamotany** [comment]
It will only handle IE but older wersions of FF/Edge dont have fetch. AFAIK fetch is not available on node so we need that polyfill for node.

**Comment by ferrannp** [comment]
Waiting for `gluestick-shared` to be in gluestick repo.

**Comment by pawlucci** [comment]
We've finally decided to update axios #801 to newest version and do not use `fetch` instead of this because after internal discussions we can't see many benefits of this change. Going to close this.
