### ISSUE TITLE
How do I run it on heroku/dokku?

### ISSUE THREAD

**Issue by ilyadoroshin** [TrueCar/gluestick#537]
Hi, guys! 

Gluestick looks awesome! There's only one question, how do I run it on heroku/dokku instance as server-side renderer? What do I need for that? (couldn't find any docs about it)

**Comment by toddw** [comment]
Hi @ilyadoroshin!
GlueStick makes creating a docker image very simple by simply typing `gluestick dockerize {tag_name}`. You can use the docker image with services that allow docker hosting.

I haven't tried Heroku until after checking out your comment but they do support docker containers https://devcenter.heroku.com/articles/container-registry-and-runtime. More specifically I think you would want to follow the instructions for [pushing an existing image](https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image).

That being said, I tried doing this with Heroku but I wasn't able to get it to successfully run for the following reasons:
1. GlueStick cli was not available when switching to a non root user: [run the image as a non root user] (https://devcenter.heroku.com/articles/container-registry-and-runtime#run-the-image-as-a-non-root-user)
  - I was able to work around this by installing `gluestick` as an app dependency and then creating my own Dockerfile
2. GlueStick in production mode uses pm2 to manage processes. By default this will try to run as many instances as CPU cores that it finds. With the memory limit in a free/hobby heroku container being 512mb, running multiple instances of the app combined with the fact that we use `babel-core/register` on startup to compile code at runtime… This was causing my free heroku dyno to hit a max memory error.
 - I tried working around this by setting MAX_INSTANCES=1 but this did not help.

To make both of those changes, it required me to create my own Dockerfile instead of what happens for free with `gluestick dockerize {tag_name}`.


# Trying to get GlueStick to run on Heroku
## Currently this does not work due to memory limit issues

1. Create Dockerfile in root folder with the following contents:
```
FROM truecar/gluestick:0.10.24
ADD . /app

#RUN npm install
#RUN npm install source-map
RUN ASSET_URL=__GS_ASSET_URL__ gluestick build
RUN useradd -m myuser
USER myuser
CMD npm start --- -P
```
1. docker build . -t {app-name}
1. heroku login
1. heroku plugins:install heroku-container-registry
1. heroku container:login
1. docker tag {image-name} registery.heroku.com/{app-name}/web
1. docker push registry.heroku.com/{app-name}/web
1. heroku open -a {app-name}

## GlueStick v2 is currently in development and it could solve this problem because we plan to start pre-compiling apps so they shouldn't require as much memory in production

**Comment by toddw** [comment]
The previous _might_ work if you had a box with a higher memory limit. This is a valid issue. We would like to support heroku so I will leave this issue open.

**Comment by ilyadoroshin** [comment]
@toddw thanks man! is there anything i can help with? :)

**Comment by toddw** [comment]
We would love to have help!
Our v2 board is here: https://github.com/TrueCar/gluestick/projects/2
*All of those tickets are pretty much accounted for…* but I don't think we have anything to address heroku or dokku hosting.

I don't know much about dokku, can you deploy an existing docker image to dokku? I think it would be helpful if someone could write up instructions on how to do that

**Comment by ilyadoroshin** [comment]
@toddw ok, will try to find some time
thanks!

**Comment by toddw** [comment]
I know this isn't exactly what you asked for but have you tried [now.sh](https://zeit.co/now)? I just tried publishing a GlueStick app with that tool and it worked great!

## Instructions for now.sh
1. Install now.sh
2. Create symbolic link to Dockerfile used by gluestick: `ln -s src/config/.Dockerfile Dockerfile
3. `now`

Example: https://gs-aabbcc-nsinzqglbf.now.sh/
https://gs-aabbcc-nsinzqglbf.now.sh/_src
