### ISSUE TITLE
-E CLI argument is inconsistent

### ISSUE THREAD

**Issue by toddw** [TrueCar/gluestick#986]
It is a little confusing that the -E argument for `gluestick generate` is used vs `gluestick start`. Would it be worth coming up with a more unified approach to this?

**Comment by zamotany** [comment]
What do you mean by unified approach? Both `generate` and `start` command use `-E` for almost same thing - specify entrypoint (or group of them in `start` cmd).

**Comment by toddw** [comment]
Compare the two use cases. When starting you use -E with a URL. When using generator you use a folder path.

**Comment by zamotany** [comment]
I see. So any idea how to unify this? We have because `start` uses `src/entries.json` to know what app to build and serve, and the `key` (eg `/home`) is required but `name` not. If we would want to use `name` it would need to be a requirement. But `generate` uses app folder name, and there might be some cases where `name` would mismatch it's app folder name.

**Comment by toddw** [comment]
Would we have too many collisions if we allowed name, folder path or url path?

For example:
`gluestick start -E sampleApp`
`gluestick start -E /sample-app`
`gluestick start -E apps/sampleApp`
`gluestick generate component Hello -E sampleApp`
`gluestick generate component Hello -E /sample-app`
`gluestick generate component Hello -E apps/sampleApp`

At first I thought there would be collisions but as I'm thinking about it… If we don't allow app names to have a slash in them then we wont have a collision between name and route or file path. So then the only confusing part is between if names that start with a forward slash vs ones that start with `apps`.

I'm not saying we should do this but I would like to see what others thing. If this is too risky then maybe we would want to consider picking 1 of the three options and keeping it consistent between the two commands. I'd love more opinions to weigh in on this

**Comment by sethbattin** [comment]
I think it should match as loosely as possible.  I got used to it, but it was initially tough to guess the correct format for url for `start`.  It would also be good if the command could be run from any path within a gluestick project without error, rather than solely at the root.  I think walking up the directory tree would help with that.

First, walk up the directory tree until `entries.json` is found

If given option `-E`:

- partial string match on `key`, `key[value]`, and `routes` to determine path. 
- - in CFE 'used', 'prospect', or 'dealer'
- collect all unique app matches 
- - if zero matches, exit with error
- - if one match, use it (with confirmation but overridable by `-y`?)
- - If there is more than one match, request more specific argument (or see last paragraph)

If no `-E`:

- match the directory which was part of the path to the cwd of the command
- if no match, use shared
- - from `base/src/apps/foo/components/` - use `apps/foo`
- - from `base/src/apps/bar/actions` - use `apps/bar`
- - from `base/src/` - use shared

Maybe also add an interactive option, to enumerate the known apps and let the user select one

**Comment by threehams** [comment]
Looking at the Angular CLI (https://github.com/angular/angular-cli), there's this general convention:
- When creating a new app, it uses the name as-is for the folder, but converts it to PascalCase internally. This is the only command which uses the argument as a folder or file name.
- When generating a new component / filter / etc, it accepts any case, but uses kebab-case for the filename and PascalCase for the component.
- Angular CLI also has the concept of apps, and uses the `--app` option throughout the command. This accepts any case, but it always refers to the name (though it also accepts a number here since apps are stored in an array - maybe for programmatic needs?).

This is a convention throughout that CLI - you can use whatever case you want for the command, but the command always accepts one _thing_, rather than attempting to parse both case and value.

I think we should follow this, by expecting the name of the app, but accepting any case. It may reduce confusion to rename `-E / --entry` to `-A --app` to get across that the command is expecting an app name rather than an entry point. Entry point is very Webpack-specific jargon and contains both a name and URL - I feel that `app` implies a name alone.

**Comment by zamotany** [comment]
If we enforce the following limitations:

- user can supply any case when generating app, but it will be converted to camelCase
- `name` for app in `src/entries.json` must be camelCase (if generated using `generate app` it will be automatically converted to camelCase)
- `name` for app must be the same as app's directory name - you can't use `"name": "userProfile"` for app `profile` 
- app `key` (url) in `src/entries.json` must be kebab-case
- apps group must be camelCase (in `src/entries.json`)
- `start` command accepts only camelCase value for `-E` or `-A` - if it starts with `/` it will be treated as single app otherwise as a group of apps
- `generate` and `destroy` command accepts only camelCase value for `-E` or `-A`

So in a nutshell app's name will be the same as it's directory name - camelCase.

Entity name for `component`, `container` and `reducer` generators will stay the same:
- PascalCase for `component`
- PascalCase for `container`
- camelCase for `reducer`

Example:
```
gluestick generate app userProfile
// or
gluestick generate app UserProfile
// or
gluestick generate app user-profile
```
would generate app `userProfile` and add it to `src/entries.json`:
```
{
    "/user-profile": {
        "name": "userProfile",
        "group": ["exampleGroup"] // <- added manually
        ...
    }
}
```
so then you can use:
```
gluestick start -A /userProfile
gluestick start -A userProfile
```
```
gluestick generate ... ... -A userProfile
gluestick destroy ... ... -A userProfile
```

How about that?

**Comment by toddw** [comment]
I think we should allow people to use whatever key they want since it is part of the url

**Comment by zamotany** [comment]
- [x] update `start`, `generate` and `destroy` commands docs if necessary
- [x] add option `A, app` to `start`, `generate` and `destroy` commands
- [x] covert app name to camelCase
- [x] update `start-client` and `start-server`to use either `entrypoints` or `app` option
- [x] update `config/prepareEntries.js` to properly resolve names using `name` or `group`
- [x] if `app.name` is not defined in `src/entries.json` use camelCased `key`
